---
id: heyitsme
links:  []
entrypoint: service.raku
name: heyitsme
endpoints: 
  - 
    id: https
    name: HTTPS
    port-env: HEYITSME_PORT
    host-env: HEYITSME_HOST
    protocol: https
env:  []
cro: 1
ignore:
  - MongoDB.log
...